apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000

  type: LoadBalancer
# loadBalancerIP: 127.0.0.1
